config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resources :sessions, only: [:new, :create, :destroy]

  resources :cipher, only: %i[index show create] do
    get :decrypt, on: :member
  end

  get :signup, to: 'users#new', as: :signup
  get :login, to: 'sessions#new', as: :login
  get :logout, to: 'sessions#destroy', as: :logout

  root to: 'cipher#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cipher_text.rb
class CipherText < ApplicationRecord
  belongs_to :user

  scope :latest, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :cipher_texts, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  protected

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/cipher_controller.rb
class CipherController < ApplicationController
  def index
    @cipher_texts = @current_user.cipher_texts.latest if @current_user
    @cipher_form = @current_user.cipher_texts.build if @current_user
  end

  def create
    cipher_params.merge!(text: cryptor.encrypt(cipher_params[:text]))
    @cipher_form = @current_user.cipher_texts.create(cipher_params)

    redirect_to action: :index
  end

  def show
    @cipher = @current_user.cipher_texts.find(params[:id])
  end

  def decrypt
    @cipher = @current_user.cipher_texts.find(params[:id])
    @decrypt_text = Cipher.new(@cipher.text, cipher_params[:shift]).decrypt(@cipher.text)
  end

  private

  def cryptor
    @cryptor ||= Cipher.new(cipher_params[:text], cipher_params[:shift])
  end

  def cipher_params
    @cipher_params ||= params.require(:cipher_text).permit(:text, :shift, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Email or password is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to :cipher_index, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/cipher/decrypt.html.erb
<%= @decrypt_text %>
<%= link_to 'Enter to encrypted text', cipher_path(@cipher) %>

app/views/cipher/index.html.erb
<h1>Create your Caesar cipher</h1>

<% if @current_user %>
  Logged in as <%= @current_user.email %>.
  <%= link_to 'Log Out', logout_path %>
<% else %>
  <%= link_to 'Sign Up', signup_path %> or
  <%= link_to 'Log In', login_path %>
<% end %>
<p id=”notice”><%= notice %></p>

<% if @current_user %>

  <hr>
  <%= form_for @cipher_form, url: { action: :create } do |f| %>
    <%= f.label :text %>
    <%= f.text_area :text %>
    <%= f.label :shift %>
    <%= f.number_field :shift %>
    <%= f.submit "Create" %>
  <% end %>


  <%- if @cipher_texts %>
    <%- @cipher_texts.each do |cipher| %>
      <p>
      <strong><%= cipher.text %></strong>
      <%= link_to 'Enter to decrypt text', cipher_path(cipher) %>
      </p>

    <%- end %>
  <%- end%>
<%- end %>

app/views/cipher/show.html.erb
<%= form_for @cipher, url: { action: :decrypt }, html: { method: :get } do |f| %>
  <%= @cipher.text %>
  <%= f.number_field :shift, value: nil, placeholder: 'Enter key to decrypt' %>
  <%= f.submit 'decrypt text' %>
<%- end %>

<%= link_to 'Back to all encrypted texts', cipher_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caesar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div id='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', cipher_index_path %>